workflows:
  build_unsigned_ipa:
    name: Build StuFlow unsigned IPA
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        APP_NAME: "StuFlow"                # Tên app (trùng tên .app trong Xcode)
        BUNDLE_ID: "com.stuflow.app"      # Bundle identifier
        XCODE_WORKSPACE: "ios/StuFlow.xcworkspace"  # nếu bạn dùng .xcworkspace
        # nếu project có .xcodeproj thay dòng trên bằng: ios/StuFlow.xcodeproj
        XCODE_SCHEME: "StuFlow"           # Scheme trong Xcode
      node: "20"
      xcode: "latest"
      cocoapods: "default"

    scripts:
      - name: Checkout + Install Node deps
        script: |
          echo "### Install JS deps"
          npm ci

      - name: Expo prebuild (only if expo managed)
        script: |
          if [ -f package.json ] && grep -q "\"expo\"" package.json; then
            echo "Detected Expo in package.json -> running expo prebuild"
            npx expo prebuild --no-install || true
          else
            echo "Not an Expo-managed project or expo not found, skipping prebuild"
          fi

      - name: Install CocoaPods (iOS)
        script: |
          if [ -d ios ]; then
            echo "Installing CocoaPods in ios/"
            cd ios
            pod install --repo-update || pod install
            cd ..
          else
            echo "No ios/ folder found -> aborting"
            exit 1
          fi

      - name: Archive app (no codesign)
        script: |
          set -o pipefail
          echo "Archiving with xcodebuild (attempt no-codesign)"
          ARCHIVE_PATH="$CM_BUILD_DIR/${APP_NAME}.xcarchive"
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee "$CM_BUILD_DIR/xcodebuild-archive.log"

      - name: Create unsigned .ipa from .xcarchive
        script: |
          echo "Packaging unsigned .ipa"
          ARCHIVE_PATH="$CM_BUILD_DIR/${APP_NAME}.xcarchive"
          APP_PATH="$ARCHIVE_PATH/Products/Applications/${APP_NAME}.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: .app not found at $APP_PATH"
            ls -la "$ARCHIVE_PATH" || true
            exit 1
          fi
          mkdir -p $CM_BUILD_DIR/ipa/Payload
          cp -R "$APP_PATH" "$CM_BUILD_DIR/ipa/Payload/"
          cd $CM_BUILD_DIR/ipa
          zip -qry "$CM_BUILD_DIR/${APP_NAME}.ipa" Payload
          echo "Unsigned IPA created: $CM_BUILD_DIR/${APP_NAME}.ipa"

      - name: List artifacts
        script: |
          echo "Artifacts:"
          ls -la $CM_BUILD_DIR/*.ipa || true
          ls -la $CM_BUILD_DIR/xcodebuild-archive.log || true

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/xcodebuild-archive.log
