workflows:
  ios-unsigned:
    name: Build iOS unsigned .ipa (Expo)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          yarn install || npm install
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --no-install
          cd ios
          pod install
          cd ..
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild -workspace StuFlow.xcworkspace \
           -scheme StuFlow \
           -configuration Release \
           -sdk iphoneos \
           -archivePath ./build/StuFlow.xcarchive \
           CODE_SIGN_IDENTITY="" \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGNING_ALLOWED=NO \
           DEVELOPMENT_TEAM="" \
           archive
          xcodebuild -exportArchive \
           -archivePath ./build/StuFlow.xcarchive \
           -exportPath ./build/ipa \
           -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
             <key>method</key><string>ad-hoc</string>
             <key>signingStyle</key><string>manual</string>
             <key>compileBitcode</key><false/>
             <key>signingCertificate</key><string></string>
             <key>signingIdentity</key><string></string>
             <key>provisioningProfiles</key><dict/>
             <key>teamID</key><string></string>
           </dict>
           </plist>') \
           CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $CM_BUILD_DIR/*.ipa
