name: Build iOS IPA

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn build
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npx expo prebuild  # Nếu dùng Expo bare
          npm run build-ios:ci # hoặc script build của bạn

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Build IPA
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          cd ios
          fastlane match development   # tạo chứng chỉ dev / profile tự động
          fastlane build               # build .ipa
